### ISSUE TITLE
Cannot login on some cloudrons

### ISSUE THREAD

**Issue by gramakri** [cloudron-io/gogs-app#1]

**Comment by Unknwon** [comment]
What is the current Gogs version runs on Cloduron?

**Comment by gramakri** [comment]
@Unknwon i reported this issue here https://github.com/gogits/gogs/issues/2040 . Our demo cloudron uses the credentials admin / admin. I have now worked it for now by changing the demo cloudron credentials to cloudron / cloudron :-)

**Comment by gramakri** [comment]
Nothing to fix here, closing.
